### ISSUE TITLE
Remove pytest dependency?

### ISSUE THREAD

**Issue by spookylukey** [adamchainz/pytest-is-running#54]
### Description

Does this need to have an `install_requires` dependency on pytest?

Specifically, this means that installing `pytest-is-running` means you get pytest installed, even if you don't need that (e.g. in production). I would have thought that, given the implementation and the intended usage, that we should be able to avoid this hard dependency.

**Comment by adamchainz** [comment]
Very good point! Fixed in #55 and released in 1.3.0.

Btw I've been considering dropping this package and only recommending `"pytest" in sys.modules`, which is just as good for most use cases.
